name: "Check XPs"

on:
  pull_request:
    paths:
     - 'app/lib/experiments/**.ts'
    branches:
    - main

jobs:
  get_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
   
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: app/lib/experiments/*.ts
  
      - name: Check XPs
        id: check-xpsid
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install typescript ts-node
      - run: npx ts-node script/check-xps.ts ${{ steps.changed-files-specific.outputs.all_changed_files }}
        
      - name: Delete old comment
        uses: peter-evans/delete-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          delete-including-replies: true
          delete-all-replies: true
          delete-all-comments: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.check-xpsid.outputs.stdout }}
          token: ${{ secrets.GITHUB_TOKEN }}