name: "Check XPs"

on:
  pull_request:
    paths:
     - 'app/lib/experiments/**.ts'
    branches:
    - master

jobs:
  get_files:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
   
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: app/lib/experiments/*.ts
  
      - name: Check XPs
        id: check-xpsid
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm install ts-node
        - run: script/check-xps.ts ${{ steps.changed-files-excluded.outputs.all_changed_files }}